### ISSUE TITLE
Head Vs wall...

### ISSUE THREAD

**Issue by fineskimo** [Irmitya/bone_layer_manager#6]
Hey hope all is good, *cuts to chase* I'm currently trying to figure out a way to create a "custom" custom properties popup for creating enum properties... I'm at a brick wall right now so thought you might be able to point me in the right direction?? or at least tell me it's not possible.. haven't added of the coding attempts to the fork, just sand-boxing it for now...
 
![Capture](https://user-images.githubusercontent.com/11440652/62162121-6f052400-b30f-11e9-9a53-3e40b2b7b653.PNG)

**Comment by Irmitya** [comment]
I don't know what you mean. 

1) When adding constraints, I want numerous sub-properties associated with it, so I use 
**CollectionProperty**. 
What a collection property does is add a root property that behaves like a list, where you can only add items to it by using a sub_fuction  [sub_group = root.add()]
each sub_group then behaves like a PropertyGroup, wherein you can insert properties however you want. 

2) My reload addon uses a dynamic **EnumProperty** list 
that scans the available addons, to find their names to be used. 

An Enum list can only reference Strings, 


An enum list that "DOES" something after you click one of the items, is either an operator that invokes an enum search menu, or it's an enum property that has a function to run in its "update" property.

**Comment by fineskimo** [comment]
It's really just about representation in the custom properties panel:

For example the following snippet would create a nice 'keyable' dropdown in the panel.
It's really just a thought that I got caught up in... 

import bpy

def update_enum(self, context):
    print(self, self.test_enum, context)

bpy.types.PoseBone.test_enum = bpy.props.EnumProperty(
    items=(
        ('state_1', 'Name 1','Discript_1'),
        ('state_2', 'Name 2','Discript_2'),
        ('state_3', 'Name 3', 'Discript_3'),
    ),
    name="test_enum",
    default="state_1",
    update=update_enum
)

bpy.data.objects["Armature"].pose.bones["Bone"].test_enum = "state_1"

**Comment by Irmitya** [comment]
https://blender.stackexchange.com/questions/10910/dynamic-enumproperty-by-type-of-selection
https://docs.blender.org/api/master/bpy.props.html?highlight=enumproperty#bpy.props.EnumProperty

```
import bpy

def enum_function(self, context):
    # obj = context.object
    obj = self
        # self = the first line higher than wherever the property is assigned

    if obj.keys():
        items = list()
    else:
        # empty lists return a TypeError when you try to access them in python
        # It may not "stop" anything but I rather avoid all errors
        items = [(  # the sets of items have to be a tuple
            'none', "No Items", "Insert custom properties to define items",
            'WARNING', 1  # This line is optional, for displaying icons
        )]
    for (ind, name) in enumerate(obj.keys()):
        if name.startswith("RIGUI"):
            items.append((
                name,
                "UI: " + name,  # Text displayed for the item
                "Is a UI item",  # Shown when hovering mouse
                "ARMATURE_DATA",  # an icon to display
                ind + 1,  # when using icons, all enums must have unique ID#
            ))
        else:
            items.append((
                'error-' + name,
                f"xX -- {name} -- Xx",
                "Not a ui",
                'ERROR',  # display an error icon for no reason
                ind + 1,
            ))
    return items


def register():
    bpy.types.Object.dynamic_enum = bpy.props.EnumProperty(
        items=enum_function,
        name="Dyna Enum",
        description="This list will change based on Custom Properties",
    )

def unregister():
    del(bpy.types.Object.dynamic_enum)

if __name__ == "__main__":
    register()

```

**Comment by fineskimo** [comment]
Legend... thanks.

**Comment by Irmitya** [comment]
@fineskimo You have to manually enable Issues, for people to post issues, in forks. 
You can also enable Discussions.
